Descent/users/models.py
from Descent import mongo, login_manager
from flask_login import UserMixin


@login_manager.user_loader
def load_user(username):
	user = mongo.db.users.find_one({"username": username})
	if not user:
		return None
	return User(user['username'])



class User():

	def __init__(self, username):
		self.username = username

	def is_authenticated(self):
		return True

	def is_active(self):
		return True

	def is_anonymous(self):
		return False

	def get_character(self):
		user = mongo.db.users.find_one({"username": username})
		return user["character"]

	def get_id(self):
		return self.username

Descent/users/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, SubmitField, PasswordField
from wtforms.validators import ValidationError, DataRequired, EqualTo, Length
from Descent.users.models import User
from Descent import mongo


class LoginForm(FlaskForm):
    username = StringField("Username", validators=[DataRequired()])
    password = PasswordField("Password", validators=[DataRequired()])
    submit = SubmitField("Login")


class RegisterForm(FlaskForm):
    username = StringField(
        'Username',
        validators=[
            DataRequired(),
            Length(min=2, max=20)])
    password = PasswordField('Password', validators=[DataRequired()])
    password_confirm = PasswordField(
        'Confirm Password',
        validators=[
            DataRequired(),
            EqualTo('password')])
    submit = SubmitField('Create Account')

    def validate_username(self, username):
        username = mongo.db.users.find_one({"username":username.data})
        if username:
            raise ValidationError('Error: That Username is already taken. ')

Descent/users/routes.py
from flask import render_template, url_for, flash, redirect, Blueprint
from flask_login import current_user, login_user, logout_user
from Descent import mongo, bcrypt
from Descent.users.forms import LoginForm, RegisterForm
from Descent.users.models import User
users = Blueprint(
	'users',
	__name__,
	template_folder='templates/users/',
	static_folder="static/users")


@users.route("/login", methods=["GET", "POST"])
def login():
	form = LoginForm()

	if current_user.is_authenticated:
		return redirect(url_for('site.home'))

	if form.validate_on_submit():
		user = mongo.db.users.find_one({"username": form.username.data})
		if user and bcrypt.check_password_hash(user['password'], form.password.data):
			user_obj = User(user["username"])
			login_user(user_obj)
			return redirect(url_for('site.home'))
		else:
			flash('Login Failed. Check Username or Password', 'danger')
	return render_template('login.html', title='login', form=form)


@users.route("/register", methods=["GET", "POST"])
def register():
	form = RegisterForm()
	if form.validate_on_submit():
		hashed_pass = bcrypt.generate_password_hash(form.password.data)
		username = form.username.data
		user = mongo.db.users
		user.insert({
			'username': username,
			'password': hashed_pass,
			'friends': [],
			'unlocks': []
			})

		return redirect(url_for('users.login'))
	return render_template("register.html", form=form)


@users.route("/logout")
def logout():
	logout_user()
	return redirect(url_for("site.home"))

Descent/users/templates/users/login.html
{% extends "users_layout.html" %}

{% block body %}




<div class="container account_box">
  <legend class="text-center pt-3 pb-2"><a href="{{ url_for('site.home') }}">Descent</a></legend>
  <hr>
  <form method='POST'>
    {{ form.hidden_tag() }}
    <fieldset class="form-group">
      <div class="form-group">
        <label class="form-control-label">{{ form.username.label }}</label>
        <div>
          {% if form.username.errors %}
            {{ form.username(class="form-control form-control-lg is-invalid txtbox") }}
            <div class="invalid-feedback">
              {% for error in form.username.errors %}
                <span>{{ error }}</span>
              {% endfor %}
            </div>  
          {% else %}            
            {{ form.username(class="form-control form-control bg-black txtbox") }}
          {% endif %}
        </div>
      </div>
      <div class="form-group">
        <label class="form-control-label">Password</label>
        <div>
          {% if form.password.errors %}
            {{ form.password(class="form-control form-control-lg is-invalid txtbox") }}
            <div class="invalid-feedback">
              {% for error in form.password.errors %}
                <span>{{ error }}</span>
              {% endfor %}
            </div>  
          {% else %}            
            {{ form.password(class="form-control bg-black form-control txtbox") }}
          {% endif %}
        </div>
      </div>
      <div class="form-group">
      {{ form.submit(class="btn btn-outline-success" ,style="width:100%") }}
    </div>
    </fieldset>
  </form>
  <hr>
  <p class="pb-5 text-center">No account yet? <a href="{{ url_for('users.register') }}">Create an Account!</a></p>
</div>
{% endblock %}

Descent/users/templates/users/register.html
{% extends "users_layout.html" %}

{% block body %}




  <div class="container account_box">
    <legend class="text-center pt-3 pb-2"><a href="{{ url_for('site.home') }}">Descent</a></legend>
    <hr>
    <form method='POST'>
      {{ form.hidden_tag() }}
      <fieldset class="form-group">
        <div class="form-group">
          <label class="form-control-label">{{ form.username.label }}</label>
          <div>
            {% if form.username.errors %}
              {{ form.username(class="form-control form-control-lg is-invalid txtbox") }}
              <div class="invalid-feedback">
                {% for error in form.username.errors %}
                  <span>{{ error }}</span>
                {% endfor %}
              </div>  
            {% else %}            
              {{ form.username(class="form-control form-control txtbox") }}
            {% endif %}
          </div>
        </div>
        <div class="form-group">
          <label class="form-control-label">{{ form.password.label }}</label>
          <div>
            {% if form.password.errors %}
              {{ form.password(class="form-control form-control is-invalid txtbox") }}
              <div class="invalid-feedback">
                {% for error in form.password.errors %}
                  <span>{{ error }}</span>
                {% endfor %}
              </div>  
            {% else %}            
              {{ form.password(class="form-control form-control txtbox") }}
            {% endif %}
          </div>
        </div>
        <div class="form-group">
          <label class="form-control-label ">{{ form.password_confirm.label }}</label>
          <div>
            {% if form.password_confirm.errors %}
              {{ form.password_confirm(class="form-control form-control is-invalid txtbox") }}
              <div class="invalid-feedback">
                {% for error in form.password_confirm.errors %}
                  <span>{{ error }}</span>
                {% endfor %}
              </div>  
            {% else %}            
              {{ form.password_confirm(class="form-control form-control txtbox") }}
            {% endif %}
          </div>
        </div>
        <div class="form-group">
        {{ form.submit(class="btn btn-outline-success" ,style="width:100%") }}
      </div>

      </fieldset>
    </form>
    <hr>
  <p class="text-center pb-4">Already have an account? <a href="{{ url_for('users.login') }}">Login!</a></p>
  </div>
{% endblock %}

Descent/users/templates/users/users_layout.html
{% extends "general_layout.html" %}

{% block head %}

<link href="{{ url_for('users.static', filename='css/user_style.css') }}" rel="stylesheet">

{% endblock %}

{% block body %}

{% with messages = get_flashed_messages(with_categories=true) %}
  {% if messages %}
    {% for category, message in messages %}
      <div class="alert alert-{{ category }} alert-dismissible fade show text-center container mt-3" style="width:50%">
        {{ message }}
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
    {% endfor %}
  {% endif %}
{% endwith %}

{% endblock %}